apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Postgres-org-dev
    type: postgres
    access: proxy
    url: postgres:5432
    database: operative_db
    user: operative
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    editable: false
